### PR TITLE
stabilization of OSMScout

### PR DESCRIPTION
**Pull request by andrejcampa**
have changed two apparmor policies to enable keep-display-on
modified two qml files, mostly reordering to make it more stable

### CODE REVIEW

**Comment by fransschreuder** [comment]
Hello Andrej,

I have merged your changes, however I don't like everything you changed:
*First of all the quick zooming is broken, it now only zooms after re-rendering the map. The old version (my head) was scaling the current (already rendered) map before actually rendering the map. This was done in order to have a snappier feel while pinch zooming / moving.
*In your pull request (main.qml) there was a typo on line 585 you typed delta.y in stead of deltaY (gave a runtime error)
*I have now completely reverted your pull request, later I will cherry pick the good changes, as the change to local variables (properties) in main.qml are actually good, I don't agree it's more stable though.
*The only thing I have kept are the keep-display-on tags in apparmor

**Comment by andrejcampa** [comment]
hi i have newer code with quick move, but quickzoom does not work... i have
disabled quick move and quickzoom,however yesterday i have fixed quickmove
and improved zooming so it actually zoom to place where you have started
pinch zooming... but calling quickzoom and quick move together will cause
that one function is not rendered...

If you want I can send you the main qml file, when i turn the computer on.
27. nov. 2015 20.27 je oseba "Frans Schreuder" notifications@github.com
napisala:

**Comment by fransschreuder** [comment]
yes, please send me the files, I can cherry-pick useful changes from it.

**Comment by andrejcampa** [comment]
Hi,

if it helps you, I am enclosing the new main.qml.
I know the changes are not the best, but that way I was able to run the
program. Otherwise after 5 to 10 minutes the program crashed, as you
allready observed since the library is not thread safe.
However if you manage that the only once these functions are called then
the program will not fail
routingModel.setStartAndTarget
map.move
map.zoom

These can be easily seen in routingdialog.qml if you press 10 or 20 times
in a row the Route button, there is high chance the program will crash
without "delay" I have implented, you can easily decrease it to 1s or less.

Another thing if you want the blue color of route, you would have to change
all the standard.oss files in map directories
http://schreuderelectronics.com/osm/
the line

  COLOR routeColor                 = #ff000088;

to
  COLOR routeColor                 = #0000ff88;

the red is not seen on some roads. Another thing is if maps are
allready downloaded then you have to change it in local directory.

Regards

Andrej

2015-11-27 20:39 GMT+01:00 Andrej Campa andrejcampa@gmail.com:

**Pull request merged**
